version: '3.8'

services:
  backend:
    build: ./backend
    container_name: inventoscan-backend
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-placeholder}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-placeholder}
      - ENVIRONMENT=${ENVIRONMENT:-production}
    networks:
      container-vlan200:
        ipv4_address: 10.2.200.101  # Feste IP
    
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: inventoscan-frontend  
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      container-vlan200:
        ipv4_address: 10.2.200.100  # Feste IP

networks:
  container-vlan200:
    external: true
